# TensorFlow gradients

This notebook demonstrates how to compute gradients with TensorFlow.

Please note that some techniques you are about to see below (e.g. `tf.function` and `tf.GradientTape`) have not been fully introduced yet, but certainly will be later on in this tutorial.

In [ ]:
# imports
import tensorflow as tf

In the next cell, we are going to build the following graph:

![](https://mermaid.ink/img/pako:eNo9jz0OwjAMRq8SeaUd6JiBCTYmWL1YjUMrNUkVEolSVeIsHI2T4Ko_nj6_70mWR6iDYdDwiNQ36npDr2ReqizLkwr9cUQ4IEwLHna87BI2Uon4-3x39T0Xa7XJ1SJb9FCA4-ioNXJ6nHuE1LBjBC3RsKXcJQT0k6i5N5T4YtoUImhL3ZMLoJzCffA16BQzb9K5JfnErdb0BwKERE8)

We define all computations in a separate function that returns both the function result itself and gradients of interest for further inspection / printing. The inputs to this function are the values of the nodes `x`, `y` and `z`.

It is your task to define the operations and to derive the partial gradients using [`tf.gradients`](https://www.tensorflow.org/api_docs/python/tf/gradients).

*Side note*: The function is decorated by [`tf.function`](https://www.tensorflow.org/api_docs/python/tf/function) which - at least for now - defines the scope in which gradients are tracked and accessible.


In [ ]:
@tf.function
def func(x, y, z):
    # all input tensors are given as arguments

    # define operations
    q = x + y
    f = q * z

    # return multiple values in a 2-tuple,
    # e.g. function results and gradients
    return f, tf.gradients(f, [x, y, z])

Now we call the function with example values and see if the gradients make sense. Please note that, instead of passing normal floats, we are using `tf.constant` tensors.

In [ ]:
f, gradients = func(
    x=tf.constant(-2.0),
    y=tf.constant(5.0),
    z=tf.constant(-4.0),
)

In [ ]:
# check gradients
print(gradients)

[<tf.Tensor: shape=(), dtype=float32, numpy=-4.0>, <tf.Tensor: shape=(), dtype=float32, numpy=-4.0>, <tf.Tensor: shape=(), dtype=float32, numpy=3.0>]


`gradients` is a list of tensors. You can call `tensor.numpy()` to access the numeric value as a numpy array.

Do they match your expectation?

## Now you

Define some more complex graphs and compute their gradients.

A good starting point is the collection of [math operations](https://www.tensorflow.org/api_docs/python/tf/math).

*Side note*: For very complex graphs it's sometimes useful to visualize them. The graph above was created with the [mermaid live editor](https://mermaid.live/edit#pako:eNo9jz0OwjAMRq8SeaUd6JiBCTYmWL1EjUsjkR9FidRSVeIsHI2T4Cqknj6_70mWF-i9JpDwiCqM4npDJ3gm0bbtSfhwXBAOCGvB847LzqGSjsXv-7Orr634V1XuijyggwYsRauM5tPL1iOkkSwhSI6aBpWfCQHdymoOWiW6aJN8BJlipgZUTv4-u77uxTkbxY_YAtcffe9DuQ).

In [ ]:
# ...